// Emits src/generated/logo.tsx: the LocalPass mark from core/logo*.svg as
// Preact components, so the popup, options page and autofill overlay render
// the exact same logo as the toolbar/AMO icons. Run via `make icons`.
//
// The SVGs are plain attribute/element markup, which is already valid JSX
// once XML comments are dropped; the root <svg> gets the caller's class.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const core = new URL("../../core/", import.meta.url);
const jsx = (name) =>
  readFileSync(new URL(name, core), "utf8")
    .replace(/<!--[\s\S]*?-->\s*/g, "")
    .replace("<svg ", '<svg class={cls} aria-hidden="true" ')
    .trim();

const out = new URL("../src/generated/", import.meta.url);
mkdirSync(out, { recursive: true });
writeFileSync(
  new URL("logo.tsx", out),
  `// Generated by \`make icons\` from core/logo*.svg. Do not edit.
export const LogoSvg = ({ class: cls }: { class: string }) => (
  ${jsx("logo.svg")}
);

export const LogoSmallSvg = ({ class: cls }: { class: string }) => (
  ${jsx("logo-small.svg")}
);
`,
);
